### ISSUE TITLE
Additional Arguments

### ISSUE THREAD

**Issue by pzahra** [canab/fd-ant-plugin#2]
Please add a setting for additional arguments to be inserted before " -buildfile". This way we can add things such as input handlers to the command.

**Comment by canab** [comment]
Sorry, I am not able to support this plugin further. I can give commit access and of course you are free to fork.

**Comment by pzahra** [comment]
Sure, I can take write access. It's just a couple of lines.

**Comment by pzahra** [comment]
OK, that's done. I don't know where to upload the compiled stuff though. I'll go to the forums at some point to tell them there's an update.

**Comment by canab** [comment]
I think it's OK to commit the DLL
